zuul:
  routes:
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  sensitive-headers:


ratelimit:
  enabled: true
  repository: jpa
  default-policy-list:
   - limit: 2
     quota: 1
     refresh-interval: 1
     type:
       - url
       - httpmethod
  policy-list:
    token:
      - limit: 2
        quota: 1
        refresh-interval: 1
        type:





server:
  port: 9070


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_tb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true